const Types = {
  SET_PC_FAVOURITE_GAMES: 'SET_PC_FAVOURITE_GAMES',
  LOCAL_PC_FAST_SET_LIMIT_LIST: 'LOCAL_PC_FAST_SET_LIMIT_LIST',
  LOCAL_PC_FAST_SET_GAMES_LIMIT_LEVEL: 'LOCAL_PC_FAST_SET_GAMES_LIMIT_LEVEL'
}

export default Types;
