import { LOTTERY_TYPES } from './config';

export const methods: Map<string, LudanMethod> = new Map();
methods.set('ssc_zh_dx', {id: '1', title: '总和大小', methodId: '1251', method: 'zh_dx', type: LOTTERY_TYPES.SSC});
methods.set('ssc_zh_ds', {id: '2', title: '总和单双', methodId: '1251', method: 'zh_ds', type: LOTTERY_TYPES.SSC});
methods.set('ssc_wg_lhh', {id: '3', title: '万个龙虎和', methodId: '1200', method: 'wg_lhh', type: LOTTERY_TYPES.SSC});
methods.set('ssc_ww_dx', {id: '4', title: '万位大小', methodId: '1250', method: 'ww_dx', type: LOTTERY_TYPES.SSC, pos: 0});
methods.set('ssc_ww_ds', {id: '5', title: '万位单双', methodId: '1250', method: 'ww_ds', type: LOTTERY_TYPES.SSC, pos: 0});
methods.set('ssc_qw_dx', {id: '6', title: '千位大小', methodId: '1250', method: 'qw_dx', type: LOTTERY_TYPES.SSC, pos: 1});
methods.set('ssc_qw_ds', {id: '7', title: '千位单双', methodId: '1250', method: 'qw_ds', type: LOTTERY_TYPES.SSC, pos: 1});
methods.set('ssc_bw_dx', {id: '8', title: '百位大小', methodId: '1250', method: 'bw_dx', type: LOTTERY_TYPES.SSC, pos: 2});
methods.set('ssc_bw_ds', {id: '9', title: '百位单双', methodId: '1250', method: 'bw_ds', type: LOTTERY_TYPES.SSC, pos: 2});
methods.set('ssc_sw_dx', {id: '10', title: '十位大小', methodId: '1250', method: 'sw_dx', type: LOTTERY_TYPES.SSC, pos: 3});
methods.set('ssc_sw_ds', {id: '11', title: '十位单双', methodId: '1250', method: 'sw_ds', type: LOTTERY_TYPES.SSC, pos: 3});
methods.set('ssc_gw_dx', {id: '12', title: '个位大小', methodId: '1250', method: 'gw_dx', type: LOTTERY_TYPES.SSC, pos: 4});
methods.set('ssc_gw_ds', {id: '13', title: '个位单双', methodId: '1250', method: 'gw_ds', type: LOTTERY_TYPES.SSC, pos: 4});
methods.set('ssc_wq_lhh', {id: '14', title: '万千', methodId: '1273', method: '1v2', type: LOTTERY_TYPES.SSC});
methods.set('ssc_wb_lhh', {id: '15', title: '万百', methodId: '1273', method: '1v3', type: LOTTERY_TYPES.SSC});
methods.set('ssc_ws_lhh', {id: '16', title: '万十', methodId: '1273', method: '1v4', type: LOTTERY_TYPES.SSC});
methods.set('ssc_wg_lhh', {id: '17', title: '万个', methodId: '1273', method: '1v5', type: LOTTERY_TYPES.SSC});
methods.set('ssc_qb_lhh', {id: '18', title: '千百', methodId: '1273', method: '2v3', type: LOTTERY_TYPES.SSC});
methods.set('ssc_qs_lhh', {id: '19', title: '千十', methodId: '1273', method: '2v4', type: LOTTERY_TYPES.SSC});
methods.set('ssc_qg_lhh', {id: '20', title: '千个', methodId: '1273', method: '2v5', type: LOTTERY_TYPES.SSC});
methods.set('ssc_bs_lhh', {id: '21', title: '百十', methodId: '1273', method: '3v4', type: LOTTERY_TYPES.SSC});
methods.set('ssc_bg_lhh', {id: '22', title: '百个', methodId: '1273', method: '3v5', type: LOTTERY_TYPES.SSC});
methods.set('ssc_gw_lhh', {id: '23', title: '个位', methodId: '1273', method: '4v5', type: LOTTERY_TYPES.SSC});

methods.set('11x5_zh_dx', {id: '50', title: '总和大小', methodId: '2050', method: 'zh_dx', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_zh_ds', {id: '51', title: '总和单双', methodId: '2050', method: 'zh_ds', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_zhw_dx', {id: '52', title: '总和尾大小', methodId: '2050', method: 'zhw_wsdx', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_zhw_ds', {id: '53', title: '总和尾单双', methodId: '2050', method: 'zhw_wsds', type: LOTTERY_TYPES.G11X5});
// methods.set('11x5_wg_lhh', {id: '55', title: '龙虎', methodId: '2053', method: 'wg_lhh', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_ww_dx', {id: '56', title: '第一位大小', methodId: '2051', method: 'ww_dx', type: LOTTERY_TYPES.G11X5, pos: 0});
methods.set('11x5_ww_ds', {id: '57', title: '第一位单双', methodId: '2051', method: 'ww_ds', type: LOTTERY_TYPES.G11X5, pos: 0});
methods.set('11x5_qw_dx', {id: '58', title: '第二位大小', methodId: '2051', method: 'qw_dx', type: LOTTERY_TYPES.G11X5, pos: 1});
methods.set('11x5_qw_ds', {id: '59', title: '第二位单双', methodId: '2051', method: 'qw_ds', type: LOTTERY_TYPES.G11X5, pos: 1});
methods.set('11x5_bw_dx', {id: '60', title: '第三位大小', methodId: '2051', method: 'bw_dx', type: LOTTERY_TYPES.G11X5, pos: 2});
methods.set('11x5_bw_ds', {id: '61', title: '第三位单双', methodId: '2051', method: 'bw_ds', type: LOTTERY_TYPES.G11X5, pos: 2});
methods.set('11x5_sw_dx', {id: '62', title: '第四位大小', methodId: '2051', method: 'sw_dx', type: LOTTERY_TYPES.G11X5, pos: 3});
methods.set('11x5_sw_ds', {id: '63', title: '第四位单双', methodId: '2051', method: 'sw_ds', type: LOTTERY_TYPES.G11X5, pos: 3});
methods.set('11x5_gw_dx', {id: '64', title: '第五位大小', methodId: '2051', method: 'gw_dx', type: LOTTERY_TYPES.G11X5, pos: 4});
methods.set('11x5_gw_ds', {id: '65', title: '第五位单双', methodId: '2051', method: 'gw_ds', type: LOTTERY_TYPES.G11X5, pos: 4});
methods.set('11x5_wq_lhh', {id: '66', title: '一位VS二位', methodId: '2053', method: '1v2', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_wb_lhh', {id: '67', title: '一位VS三位', methodId: '2053', method: '1v3', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_ws_lhh', {id: '68', title: '一位VS四位', methodId: '2053', method: '1v4', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_wg_lhh', {id: '69', title: '一位VS五位', methodId: '2053', method: '1v5', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_qb_lhh', {id: '70', title: '二位VS三位', methodId: '2053', method: '2v3', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_qs_lhh', {id: '71', title: '二位VS四位', methodId: '2053', method: '2v4', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_qg_lhh', {id: '72', title: '二位VS五位', methodId: '2053', method: '2v5', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_bs_lhh', {id: '73', title: '三位VS四位', methodId: '2053', method: '3v4', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_bg_lhh', {id: '74', title: '三位VS五位', methodId: '2053', method: '3v5', type: LOTTERY_TYPES.G11X5});
methods.set('11x5_sg_lhh', {id: '75', title: '四位VS五位', methodId: '2053', method: '4v5', type: LOTTERY_TYPES.G11X5});

methods.set('pk10_zh_dx', {id: '100', title: '冠亚和大小', methodId: '4050', method: 'zh_dx', type: LOTTERY_TYPES.PK10});
methods.set('pk10_zh_ds', {id: '101', title: '冠亚和单双', methodId: '4050', method: 'zh_ds', type: LOTTERY_TYPES.PK10});

methods.set('pk10_1_dx', {id: '102', title: '冠军大小', methodId: '4053', method: '1_dx', type: LOTTERY_TYPES.PK10, pos: 0});
methods.set('pk10_1_ds', {id: '103', title: '冠军单双', methodId: '4053', method: '1_ds', type: LOTTERY_TYPES.PK10, pos: 0});
methods.set('pk10_2_dx', {id: '104', title: '亚军大小', methodId: '4053', method: '2_dx', type: LOTTERY_TYPES.PK10, pos: 1});
methods.set('pk10_2_ds', {id: '105', title: '亚军单双', methodId: '4053', method: '2_ds', type: LOTTERY_TYPES.PK10, pos: 1});
methods.set('pk10_3_dx', {id: '106', title: '季军大小', methodId: '4053', method: '3_dx', type: LOTTERY_TYPES.PK10, pos: 2});
methods.set('pk10_3_ds', {id: '107', title: '季军单双', methodId: '4053', method: '3_ds', type: LOTTERY_TYPES.PK10, pos: 2});
methods.set('pk10_4_dx', {id: '107', title: '第四名', methodId: '4053', method: '4_dx', type: LOTTERY_TYPES.PK10, pos: 3});
methods.set('pk10_4_ds', {id: '107', title: '第四名', methodId: '4053', method: '4_ds', type: LOTTERY_TYPES.PK10, pos: 3});
methods.set('pk10_5_dx', {id: '107', title: '第五名', methodId: '4053', method: '5_dx', type: LOTTERY_TYPES.PK10, pos: 4});
methods.set('pk10_5_ds', {id: '107', title: '第五名', methodId: '4053', method: '5_ds', type: LOTTERY_TYPES.PK10, pos: 4});
methods.set('pk10_6_dx', {id: '107', title: '第六名', methodId: '4053', method: '6_dx', type: LOTTERY_TYPES.PK10, pos: 5});
methods.set('pk10_6_ds', {id: '107', title: '第六名', methodId: '4053', method: '6_ds', type: LOTTERY_TYPES.PK10, pos: 5});
methods.set('pk10_7_dx', {id: '107', title: '第七名', methodId: '4053', method: '7_dx', type: LOTTERY_TYPES.PK10, pos: 6});
methods.set('pk10_7_ds', {id: '107', title: '第七名', methodId: '4053', method: '7_ds', type: LOTTERY_TYPES.PK10, pos: 6});
methods.set('pk10_8_dx', {id: '107', title: '第八名', methodId: '4053', method: '8_dx', type: LOTTERY_TYPES.PK10, pos: 7});
methods.set('pk10_8_ds', {id: '107', title: '第八名', methodId: '4053', method: '8_ds', type: LOTTERY_TYPES.PK10, pos: 7});
methods.set('pk10_9_dx', {id: '107', title: '第九名', methodId: '4053', method: '9_dx', type: LOTTERY_TYPES.PK10, pos: 8});
methods.set('pk10_9_ds', {id: '107', title: '第九名', methodId: '4053', method: '9_ds', type: LOTTERY_TYPES.PK10, pos: 8});
methods.set('pk10_10_dx', {id: '107', title: '第十名', methodId: '4053', method: '10_dx', type: LOTTERY_TYPES.PK10, pos: 9});
methods.set('pk10_10_ds', {id: '107', title: '第十名', methodId: '4053', method: '10_ds', type: LOTTERY_TYPES.PK10, pos: 9});

methods.set('pk10_1vs10_lhh', {id: '112', title: '冠军VS第十名', methodId: '4054', method: '1v10', type: LOTTERY_TYPES.PK10});
methods.set('pk10_2vs9_lhh', {id: '113', title: '亚军VS第九名', methodId: '4054', method: '2v9', type: LOTTERY_TYPES.PK10});
methods.set('pk10_3vs8_lhh', {id: '114', title: '季军VS第八名', methodId: '4054', method: '3v8', type: LOTTERY_TYPES.PK10});
methods.set('pk10_4vs7_lhh', {id: '115', title: '第四名VS第七名', methodId: '4054', method: '4v7', type: LOTTERY_TYPES.PK10});
methods.set('pk10_5vs6_lhh', {id: '116', title: '第五名VS第六名', methodId: '4054', method: '5v6', type: LOTTERY_TYPES.PK10});
methods.set('pk10_gy_dx', {id: '117', title: '冠亚和大小', methodId: '4053', method: 'ww_dx', type: LOTTERY_TYPES.PK10, pos: 0});
methods.set('pk10_gy_ds', {id: '118', title: '冠亚和单双', methodId: '4053', method: 'ww_ds', type: LOTTERY_TYPES.PK10, pos: 0});

methods.set('k3_zh_dx', {id: '200', title: '大小', methodId: '5018', method: 'zh_dx', type: LOTTERY_TYPES.K3});
methods.set('k3_zh_ds', {id: '201', title: '单双', methodId: '5018', method: 'zh_ds', type: LOTTERY_TYPES.K3});
